### PR TITLE
Azerbaijani translation

### PR DESCRIPTION
**Pull request by adilek**
Azerbaijani locale added

### CODE REVIEW

**Comment by ai** [comment]
@adilek awesome. One more small changes: could you also translate `r18n-core/base/` file for locale?

**Comment by ai** [comment]
Does I understand correctly, that Azerbaijani doesn’t have plural system at all (“1 robot”, “2 robot**s**”)

**Comment by adilek** [comment]
I will upload the locale file in r18-core/base

Right, Azerbaijani language does not have plural system for counting. 1 item, 2 item, 10 item (without s).

**Comment by adilek** [comment]
It is done.

**Comment by ai** [comment]
Awesome! I will accept and release all changes in the evening

**Comment by ai** [comment]
Released in 2.1.4 (Bakı)

**Pull request merged**
