### PR TITLE
Add Boolean keys support

### LINKED ISSUE #152: Boolean as YAML keys
Hello!

## Problem

```yaml
# en.yml
foo:
  true: Foo is true
  false: Foo is false
```

```ruby
R18n.set('en')
=> #<R18n::I18n:0x0000556ae2f29638>

R18n.t.foo
=> Translation `foo` for en {true=>"Foo is true", false=>"Foo is false"}

R18n.t.foo.true
=> #<R18n::Untranslated:0x0000556ae24edbb0
 @filters=#<R18n::GlobalFilterList:0x0000556ae2f0aaf8>,
 @locale=Locale en (English),
 @translated_path="foo.",
 @untranslated_path="true">

R18n.t.foo[true]
=> #<R18n::Untranslated:0x0000556ae1ca41e8
 @filters=#<R18n::GlobalFilterList:0x0000556ae2f0aaf8>,
 @locale=Locale en (English),
 @translated_path="foo.",
 @untranslated_path="true">

R18n.t.foo['true']
=> #<R18n::Untranslated:0x0000556ae1a4d750
 @filters=#<R18n::GlobalFilterList:0x0000556ae2f0aaf8>,
 @locale=Locale en (English),
 @translated_path="foo.",
 @untranslated_path="true">
```

## Links

[YAML Bool Type](http://yaml.org/type/bool.html)
[YAML Reference card](http://yaml.org/refcard.html)
[Some article about this](https://makandracards.com/makandra/24809-yaml-keys-like-yes-or-no-evaluate-to-true-and-false)

## Why?

I have `@foo` variable, for example, and call `t.foo[@foo]`.

### PR DESCRIPTION
**Pull request by AlexWayfer**
Fix #152

### CODE REVIEW

**Comment by ai** [comment]
Thanks. I will release it in next few hours.

**Comment by AlexWayfer** [comment]
Thank you! I'll wait.

**Comment by ai** [comment]
Released in 2.1.8.

**Comment by AlexWayfer** [comment]
Thank you very much. Used :hugs:

**Pull request merged**
