### PR TITLE
translate base/en.yml to Vietnamese

### PR DESCRIPTION
**Pull request by nguyenvanduocit**

### CODE REVIEW

**Comment by ai** [comment]
@nguyenvanduocit do I understand correct, that there is no single (“1 robot”) and plural (“5 robot**s**”) in Vietnamese?

**Comment by ai** [comment]
And last question: “One” is translated Vietnamese to as “Một”? (I need a release name :) )

**Comment by nguyenvanduocit** [comment]
In Vietnamese have no plural like that, Just 5 robot.
"One" is "Một"

**Comment by ai** [comment]
Awesome. Thanks. It was hard work, I know :).

Just after few hours (not at home right now), I will make a release and accept easings.net PR :).

**Comment by nguyenvanduocit** [comment]
I just translated some string. Thanks for your great lib.

**Pull request merged**
