### PR TITLE
Remove outdated `no` locale

### LINKED ISSUE #166: `no` locale
I think it doesn't exist (anymore).

https://github.com/TakahikoKawasaki/nv-i18n/issues/9

### PR DESCRIPTION
**Pull request by AlexWayfer**
It duplicated `nb` locale.

Resolve #166

### CODE REVIEW

**Comment by AlexWayfer** [comment]
> R18n.locale = :no

```ruby
> R18n.method(:locale=).source_location
NameError: undefined method `locale=' for class `#<Class:R18n>'
```

:thinking: 

I think you meant `R18n.set :no`.

**Comment by ai** [comment]
Yeap. I mean removing locale will break public API.

**Comment by AlexWayfer** [comment]
Done. I hope you like this approach.

**Comment by ai** [comment]
I developer used `R18n.get.code` somewhere, this change will break code :(.

We need to fake `code` as well.

Maybe we could create `locales/no.rb` which will extends everything from `nb.rb`?

**Comment by AlexWayfer** [comment]
> I developer used R18n.get.code somewhere, this change will break code :(.
>
> We need to fake code as well.
>
> Maybe we could create locales/no.rb which will extends everything from nb.rb?

I duplicate comment from issue: in `rails-i18n` [`no` locale was renamed to `nb` and `nn` in 2010](https://github.com/svenfuchs/rails-i18n/commit/196ea80372e08941f9e9e8899e3af7b0b86e703c#diff-25099b7929778e13d340d4ba43fd4408). Without backward compability.

**Comment by ai** [comment]
OK. Anyway with all this internal changes we will need major release.

But can you add check and throw explicit error about `no>nb`, if somebody will set it.

**Comment by AlexWayfer** [comment]
> But can you add check and throw explicit error about no>nb, if somebody will set it.

Maybe deprecation warning and we can don't make major release? :thinking:

**Comment by ai** [comment]
We need a full `no` support (extend `nb` in `no.rb`) if we will make minor release.

**Comment by ai** [comment]
How you will extend `R18n::Locale::Nb` and `R18n:: 
DeprecatedLocale`? 😉

**Comment by AlexWayfer** [comment]
> How you will extend R18n::Locale::Nb and R18n:: DeprecatedLocale? :wink:

Good point! OK, `class No < Nb; include Deprecated` or `set ..., deprecated: true`.

**Comment by ai** [comment]
👍 or just put a warning to constructor 😄

**Comment by AlexWayfer** [comment]
I used [`Module#deprecate_constant`](http://ruby-doc.org/core-2.5.0/Module.html#method-i-deprecate_constant). It has no argument for replacement :pensive:

Option 2:

```ruby
class << self
  extend Gem::Deprecate
  deprecate :new, 'R18n::Locales::Nb.new', 2018, 3
end
# NOTE: R18n::Locales::No.new is deprecated; use R18n::Locales::Nb.new instead. It will be removed on or after 2018-03-01.
# R18n::Locales::No.new called from /home/alex/Projects/ruby/r18n/r18n-core/lib/r18n-core/locale.rb:82.
```

Option 3: custom message.

-----

UPD: Oh, Ruby 2.2 failed :(

**Comment by AlexWayfer** [comment]
OK, made with option 2.

**Comment by ai** [comment]
Released in 3.0

**Pull request merged**
