### PR TITLE
Move `named_variables` filter from `r18n-rails-api` to `r18n-core`

### PR DESCRIPTION
**Pull request by AlexWayfer**
Revert f59e910

### CODE REVIEW

**Comment by ai** [comment]
BTW, do you want become a maintenancer? 😄

**Comment by ai** [comment]
PR looks good

**Comment by AlexWayfer** [comment]
> BTW, do you want become a maintenancer? :smile:

I think I can try. :slightly_smiling_face: 

Like a collaborator, or member of organization for configuring some integrations (Codecov, Depfu, etc.)

After #167 I know almost the whole R18n, except Rails part, because I don't work with Rails or ActiveSomething.

**Comment by ai** [comment]
I add you to the project. What is your RubyGems’s username?

The only thing I want to ask you about is to keep a [release names](https://github.com/ai/r18n/blob/master/r18n-core/ChangeLog.md). I give a name for every release, including patch releases. It is mostly city or letter (to keep internationalization idea).

**Comment by AlexWayfer** [comment]
> I add you to the project.

Thanks! :tada: 

> What is your RubyGems’s username?

[AlexWayfer](https://rubygems.org/profiles/alexwayfer), as an everywhere (it's a bit silly, but unique username).

> The only thing I want to ask you about is to keep a release names. I give a name for every release, including patch releases. It is mostly city or letter (to keep internationalization idea).

OK, thanks, I got it. I'll try not to repeat. :sweat_smile:

**Comment by ai** [comment]
Congrats, now you have RubyGems access and you are now maintainee. Feel free to ask any question and help.

**Comment by AlexWayfer** [comment]
Thank you, I appreciate it.

**Pull request merged**
